title: Grupo de Pesquisa em Jogos
description: Um grupo dedicado a pesquisar jogos da Universidade de São Paulo - Instituto de Ciências Matemáticas e Computação.

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
